name: React Native CI/CD Pipeline # Name of the workflow for easy identification

# Define when the workflow should run
on:
  push:
    branches:
      - master # Runs on pushes to the main branch

jobs:
  build:
    name: Build iOS and Android # Job to build the app for both platforms
    runs-on: ubuntu-latest # Runs on the latest Ubuntu environment

    # Define a matrix for building on both Android and iOS
    strategy:
      matrix:
        platform: [android, ios] # This matrix will run the build job twice, once for each platform

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v4 # Uses GitHub's official action to check out the code

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Specifies Node.js version 14, which is commonly compatible with React Native

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install # Installs all project dependencies listed in package.json

      # Step 4: Run TypeScript checks
      - name: TypeScript Check
        run: npx tsc 
      
      - name: Update Java version
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'  

      # Step 5: Build for each platform using a conditional matrix
      - name: Build ${{ matrix.platform }}
        run: |
          if [ "${{ matrix.platform }}" == "android" ]; then
            cd android && ./gradlew assembleDebug
          fi
